# fly.toml file generated for shorty on 2022-08-14T19:17:40+10:00

app = "shorty"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
source="shortydb"
destination="/data"

[env]
DATABASE_URL="/data/db.sqlite3"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
