# fly.toml app configuration file generated for shorty on 2023-10-16T16:58:36+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shorty"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  DATABASE_URL = "/data/db.sqlite3"

[processes]
  app = ""

[[mounts]]
  source = "shortydb"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
